version: "3.7"

services:

  government-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vidchain/government-backend:v0.1
    container_name:  government-backend
    ports:
      - 3021:3021
    networks:
      - hydra_network
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - BASE_URL=https://dev.api.vidchain.net/demo-api
      - PORT=3021

networks:
  hydra_network:
    driver: bridge
    name: hydra_oidc_network