apiVersion: apps/v1
kind: Deployment
metadata:
  name: airline-backend-deployment
  labels:
    app: airline-backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: airline-backend
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: airline-backend
    spec:
      containers:
      - image: k8scrvidchainpro.azurecr.io/airline-backend:latest
        imagePullPolicy: "Always"
        name: airline-backend
        ports:
        - containerPort: 3031
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: airline-backend-configmap
              key: API_URL
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              name: airline-backend-configmap
              key: BASE_URL
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: airline-backend-configmap
              key: PORT
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: airline-backend-configmap
              key: REDIS_URL
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: airline-backend-configmap
              key: REDIS_PORT
        - name: WS_URL
          valueFrom:
            configMapKeyRef:
              name: airline-backend-configmap
              key: WS_URL
        - name: IDENTITY_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: airline-backend-configmap
              key: IDENTITY_PROVIDER
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: airline-api-key
              key: api-key
        - name: API_KEY_DIDKEY
          valueFrom:
            secretKeyRef:
              name: airline-api-key-did-key
              key: api-key-did-key
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: airline-client-secret
              key: client-secret
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: airline-backend-service
  labels:
    app: airline-backend
spec:
  type: ClusterIP
  ports:
  - name: "3031"
    port: 3031
  selector:
    app: airline-backend

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: airline-backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - try.vidchain.net
    secretName: tls-secret-production
  rules:
  - host: try.vidchain.net
    http:
      paths:
      - path: /demo/airlinebackend
        backend:
          serviceName: airline-backend-service
          servicePort: 3031
      - path: /airlinews
        backend:
          serviceName: airline-backend-service
          servicePort: 3031