apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajuntament-gava-frontend-deployment
  labels:
    app: ajuntament-gava-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ajuntament-gava-frontend
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ajuntament-gava-frontend
    spec:
      containers:
      - image: k8scrvidchaindev.azurecr.io/ajuntament-gava-frontend:latest
        imagePullPolicy: "Always"
        name: ajuntament-gava-frontend
        ports:
        - containerPort: 9090
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: ajuntament-gava-frontend-service
  labels:
    app: ajuntament-gava-frontend
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
  selector:
    app: ajuntament-gava-frontend

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ajuntament-gava-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /demo/gavius/$2
spec:
  tls:
  - hosts:
    - dev.vidchain.net
    secretName: tls-secret-production
  rules:
  - host: dev.vidchain.net
    http:
      paths: 
      - path: /demo/gavius(/|$)(.*)
        backend:
          serviceName: ajuntament-gava-frontend-service
          servicePort: 9090