apiVersion: v1
kind: ConfigMap
metadata:
  name: government-frontend-configmap
data:
  REACT_APP_API_URL: "https://api.vidchain.net/api/v1/"
  REACT_APP_REDIRECT_CALLBACK: "https://try.vidchain.net/demo/government/callback"
  REACT_APP_IDENTITY_PROVIDER: "https://api.vidchain.net"
  REACT_APP_DEMO: "https://try.vidchain.net/demo/government"
  REACT_APP_BACKEND_URL: "https://try.vidchain.net/demo/governmentbackend"
  REACT_APP_WS_URL: "https://try.vidchain.net"
  PUBLIC_URL: "https://try.vidchain.net/demo/government"