apiVersion: v1
kind: ConfigMap
metadata:
  name: ajuntament-gava-backend-configmap
data:
  API_URL: "https://api.vidchain.net/api/v1/"
  BASE_URL: "https://try.vidchain.net/demo/gaviusbackend"
  PORT: "9091"
  REDIS_URL: "redis"
  REDIS_PORT: "6379"
  WS_URL: "https://try.vidchain.net"
  IDENTITY_PROVIDER: "https://identitats-pre.aoc.cat"