apiVersion: v1
kind: ConfigMap
metadata:
  name: government-backend-configmap
data:
  API_URL: "https://api.vidchain.net/api/v1/"
  BASE_URL: "https://try.vidchain.net/demo/gaviusbackend"
  PORT: "3021"
  REDIS_URL: "redis"
  REDIS_PORT: "6379"
  WS_URL: "https://try.vidchain.net"